# ========================
# Kitty Terminal Config
# ========================

# Font
# font_family monospace
font_family      0xProto Nerd Font
bold_font        0xProto Nerd Font Bold
italic_font      0xProto Nerd Font Italic
bold_italic_font 0xProto Nerd Font Italic
font_size   13.0

# Cursor
cursor_shape block
cursor_blink_interval 0.6
# cursor_trail 1
# cursor_trail_decay 0.1 0.3
# cursor_trail_start_threshold 0
shell_integration no-cursor

# Window Padding
window_margin_width 0
window_margin_height 0

# Close without confirmation
confirm_os_window_close 0

# Default shell
shell bash

# ========================
# Key Mappings
# ========================

# Copy & Paste
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map shift+insert paste_from_clipboard

# Font Zoom Controls
map ctrl+plus         change_font_size all +1
map ctrl+equal        change_font_size all +1
map ctrl+kp_add       change_font_size all +1

map ctrl+minus        change_font_size all -1
map ctrl+underscore   change_font_size all -1
map ctrl+kp_subtract  change_font_size all -1

map ctrl+0            change_font_size all 0
map ctrl+kp_0         change_font_size all 0

# ========================
# YSAP Color Theme
# ========================
# Backgrounds
background #181818
foreground #bebfb8

# Base ANSI colors
color0  #181818
color1  #fe605e
color2  #8daf62
color3  #fbb065
color4  #85afd6
color5  #a983ac
color6  #85afd6
color7  #bebfb8

# Bright variants
color8  #222222
color9  #fe605e
color10 #8daf62
color11 #fbb065
color12 #85afd6
color13 #a983ac
color14 #85afd6
color15 #cfcfc6

# Cursor + selection
cursor #fbb065
selection_background #313131
# Basic colors
# foreground              #c5c5c5
# #background              #0f0f0f
# background              #181818

# selection_background #3a3f5c
# selection_foreground #ffffff
# cursor                  #ffcc00

# # Normal colors
# color0  #000000
# color1  #cc0000
# color2  #00cc00
# color3  #ffcc00
# color4  #0088cc
# color5  #cc00cc
# color6  #00cccc
# color7  #e5e5e5

# # Bright colors
# color8   #4d4d4d
# color9   #ff4444
# color10  #44ff44
# color11  #ffff44
# color12  #44aaff
# color13  #ff44ff
# color14  #44ffff
# color15  #e5e5e5

# ========================
# Tab Bar
# ========================

active_tab_foreground    #000000
active_tab_background    #ffcc00
inactive_tab_foreground  #e5e5e5
inactive_tab_background  #1a1a1a

map alt+h send_text all \eh
map alt+j send_text all \ej
map alt+k send_text all \ek
map alt+l send_text all \el

# background_opacity 0.90
# background_blur 0

# background #111111
# foreground #dddddd

# dim_opacity 0.75
cursor_trail 10
cursor_trail_decay 0.005 0.05

cursor #00eaff
cursor_width 3

cursor_blink_interval 0.2
